### ISSUE TITLE
Не удается найти pythonw

### ISSUE THREAD

**Issue by Kordex1337** [KycTik31/YMD-plus#1]
https://i.imgur.com/5VmpZ8a.png

**Comment by KycTik31** [comment]
Попробуй посмотреть папку питона, там должен быть pythonw.exe, если он там есть то вполне возможно что при установке питона ты не поставил галочку add to PATH, просто переустанови его или через Винду можно "модифицировать" (в "установка и удаление программ" -> ищешь питон -> "изменить")
Я щас не за компом, полные действия описать не могу

**Comment by alfixns** [comment]
такая же проблема, галочку поставила, но все равно ошибка. не особо разбираюсь в этом всём, помогите пожалуйста

**Comment by KycTik31** [comment]
[fixer.zip](https://github.com/KycTik31/YMD-plus/files/11537314/fixer.zip)
ПЕРЕИМЕНУЙТЕ ФАЙЛ ИЗ .zip В .ps1 (гит не дает заливать файлы другого типа)
попробуйте запустить (правой кнопкой по файлу -> Выполнить с помощью PowerShell)
у вас должно открыться и закрыться окно, после этого pythonw должен находиться, если нет, то я честно не особо имею представление в чем проблема

**Comment by alfixns** [comment]
вы скинули пустой архив, его не получается преобразовать в принципе почему-то.

**Comment by KycTik31** [comment]
> вы скинули пустой архив

Это и не архив, да и можете забить, скорее всего сегодня я выкачу ехе файл

**Comment by KycTik31** [comment]
сделал ехе, тема не актуальна
