### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by error911-prog** [KycTik31/YMD-plus#10]
Запустил батник, прошла загрузка, прошел авторизацию и тут вот такое. 
[error.txt](https://github.com/KycTik31/YMD-plus/files/12486460/error.txt)
![image](https://github.com/KycTik31/YMD-plus/assets/81414567/5548a24d-6160-42a8-9d6f-63670ae5b314)

**Comment by KycTik31** [comment]
Во первых PyQt версия более не поддерживается.
Во вторых проблема где-то в библиотеке pypresence. как это решать я не знаю

**Comment by MadnezGirl** [comment]
почему не поддерживается, но до сих пор тут? интересно, что с mac у меня запустилось только в PyQt

**Comment by KycTik31** [comment]
> почему не поддерживается, но до сих пор тут? интересно, что с mac у меня запустилось только в PyQt

на маке нет яндекс музыки или я чего-то не знаю?

**Comment by Soto4ka37** [comment]
На маке нет Edge WebWiew, поэтому будет работать только PyQt версия. На старых версиях виндовс скорее всего тоже

**Comment by KycTik31** [comment]
> На маке нет Edge WebWiew, поэтому будет работать только PyQt версия. На старых версиях виндовс скорее всего тоже

Так Яндекс музыка есть только на 10 Винде (ну 11 я в расчет не беру т.к там все тоже самое должно быть), а сторонние клиенты Я не поддерживаю

**Comment by MadnezGirl** [comment]
ну так это приложение может работать и с веб-сайтом, не только с приложением из магазина microsoft

**Comment by KycTik31** [comment]
> ну так это приложение может работать и с веб-сайтом, не только с приложением из магазина microsoft

А смысл, моя прога делалась для приложения, а не для веб версии. Для веба другие версии есть
