### ISSUE TITLE
пишит пауза когда играет трек

### ISSUE THREAD

**Issue by exer11** [KycTik31/YMD-plus#11]
![image](https://github.com/KycTik31/YMD-plus/assets/88577540/537b739d-9c24-4f0e-abad-026e33ce8956)

**Comment by KycTik31** [comment]
Слушай, Я не волшебник, мне хоть какие-то подробности нужны, че за Яндекс музыка используется, на одном ли треке это, какая из двух версий программы используется, по максимуму всего

**Comment by exer11** [comment]
на всех треках пауза, когда использую показ времени, ![image](https://github.com/KycTik31/YMD-plus/assets/88577540/d0cd7e89-1b28-44d8-9c8e-11883e654315)

**Comment by exer11** [comment]
также когда слушаю музыку, то спустя время пишет "моя волна"

**Comment by KycTik31** [comment]
Суть в то что прога читает не те значения из памяти.
Какие будут решения?
1. Не использовать функцию показа времени
2. самому искать офсеты через чит энжин и вносить их в прогу
3. ждать когда я добавлю калибровку (это будет не очень скоро, т.к помимо учебы, у меня ещё один проект на носу. Но постараюсь пораньше)
