### ISSUE TITLE
Зачем по отдельности устаналивать каждую зависимость?

### ISSUE THREAD

**Issue by penggrin12** [KycTik31/YMD-plus#12]
Вот [это](https://github.com/KycTik31/YMD-plus/blob/main/wxPython/main.py#L15-L18) все можно заменить одной строчкой:
`os.system('pip install yandex-music pypresence pymem wxPython==4.2.1 --upgrade')`

**Comment by KycTik31** [comment]
Это все равно не влияет на производительность, так что в целом не важно, в одну строчку или в несколько

**Comment by penggrin12** [comment]
На очень старом компьютере сильно вляет. пип долго (7-8 секунд) запускается.
И вот так 4 раза пип запускает при каждом запуске программы

**Comment by penggrin12** [comment]
Могу PR написать

**Comment by KycTik31** [comment]
Ты реально думаешь кто то будет запускать Винду 10, Дискорд, Яндекс музыку и мою прогу на старом компе? ☠️ (Моя прога примерно 100мб оперативы жрет, Дискорд ~600мб, Яндекс музыка ещё 100мб)

**Comment by VASNV** [comment]
> Ты реально думаешь кто то будет запускать Винду 10, Дискорд, Яндекс музыку и мою прогу на старом компе? ☠️ (Моя прога примерно 100мб оперативы жрет, Дискорд ~600мб, Яндекс музыка ещё 100мб)

Ахах, дискорд гига 2,5 - 3 жрет, так еще и дико баганное говно. А так да вопрос для чего, а именно зачем и с какой целью оно нужно.

**Comment by KycTik31** [comment]
Не вижу смысл продолжать
