### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by grygorp** [KycTik31/YMD-plus#13]
В конце установки выдаёт ошибку:
![image](https://github.com/KycTik31/YMD-plus/assets/161206042/d7d1be67-c486-411a-8834-af71f28025ea)
Я просто даже близко не понимаю что не так(

**Comment by KycTik31** [comment]
error.txt скинь

**Comment by Travol1a** [comment]
> error.txt скинь
[error.txt](https://github.com/KycTik31/YMD-plus/files/14396841/error.txt)

**Comment by Travol1a** [comment]
такая же ошибка

**Comment by KycTik31** [comment]
> > error.txt скинь
> > [error.txt](https://github.com/KycTik31/YMD-plus/files/14396841/error.txt)

а зачем ты используешь PyQt версию? я же написал что она не поддерживается

**Comment by Travol1a** [comment]
> > > error.txt скинь
> > > [error.txt](https://github.com/KycTik31/YMD-plus/files/14396841/error.txt)
> 
> а зачем ты используешь PyQt версию? я же написал что она не поддерживается
ошибка на обеих версиях одинаковая

**Comment by Travol1a** [comment]
> > > error.txt скинь
> > > [error.txt](https://github.com/KycTik31/YMD-plus/files/14396841/error.txt)
> 
> а зачем ты используешь PyQt версию? я же написал что она не поддерживается

[error.txt](https://github.com/KycTik31/YMD-plus/files/14397060/error.txt)
а, извиняюсь, не одинаковая ошибка

**Comment by KycTik31** [comment]
> [error.txt](https://github.com/KycTik31/YMD-plus/files/14397060/error.txt) а, извиняюсь, не одинаковая ошибка

я таб забыл поставить. можешь перескачать. вообще я не понимаю зачем вы питон версией пользуетесь, если я сделал exe файл

**Comment by KycTik31** [comment]
Ответа от изначального отправителя нет

**Comment by grygorp** [comment]
> > [error.txt](https://github.com/KycTik31/YMD-plus/files/14397060/error.txt) а, извиняюсь, не одинаковая ошибка
> 
> я таб забыл поставить. можешь перескачать. вообще я не понимаю зачем вы питон версией пользуетесь, если я сделал exe файл

а где exe, я не нашёл :(

(я вчера забыл приложить, а когда мне на почту гитхаб спамил я был не дома)
[error.txt](https://github.com/KycTik31/YMD-plus/files/14405824/error.txt)

**Comment by KycTik31** [comment]
> а где exe, я не нашёл :(
> 
> (я вчера забыл приложить, а когда мне на почту гитхаб спамил я был не дома) [error.txt](https://github.com/KycTik31/YMD-plus/files/14405824/error.txt)

Опять 25, PyQt версия. Сноси её

[exe здесь](https://github.com/KycTik31/YMD-plus/releases)
