### ISSUE TITLE
Моя волна и новые клиенты(last.fm)

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [KycTik31/YMD-plus#14]
Копирую issue из другого репозитория с RPC яндекс музыки, но все равно: Предлагаю добавить поддержку last.fm, потому что ранее можно было прилинковать его к яндекс музыке. Так будет поддержка и моей волны, и нового клиента с браузером. Код я реализовал у себя в проекте, [так что думаю если его переделать и улучшить можно добавить сюда](https://github.com/MIPOHBOPOHIH/YMMBBot/blob/main/ymmbbot.py#L45-L74)

**Comment by KycTik31** [comment]
Я не буду это делать по 2-м причинам
1. Проект изначально создавался для версии из ms store, поддержка браузера и нового (очень сырого) клиента не планировалась
2. Из за угасшего желания, Я не буду обновлять проект
