### ISSUE TITLE
при запуске start.bat батник просто вылетает :/

### ISSUE THREAD

**Issue by rstarxx** [KycTik31/YMD-plus#2]

**Comment by KycTik31** [comment]
Питон хоть установлен?

**Comment by rstarxx** [comment]
да

**Comment by KycTik31** [comment]
5 строчку в main.py перемести между 15 и 16

**Comment by KycTik31** [comment]
Хотя ладно я сам

**Comment by KycTik31** [comment]
Перескачай, щас должно работать

**Comment by rstarxx** [comment]
теперь устанавливается. Спасибо <3

**Comment by KycTik31** [comment]
Я оставлю открытой на минут 20 эту проблему, если что пиши
