### ISSUE TITLE
exe файла нет в архиве

### ISSUE THREAD

**Issue by alfixns** [KycTik31/YMD-plus#3]
архив новый скачала, этого файла там нет

**Comment by KycTik31** [comment]
скорее всего вы скачали сурсы
![image](https://github.com/KycTik31/YMD-plus/assets/119877617/eb6fcf4b-4f62-4167-bc85-5ea0464eccec)
надо YMD.rar (я скачал с гита)
![image](https://github.com/KycTik31/YMD-plus/assets/119877617/f08f9b8f-4f59-4316-b5b1-7a694e7e7d14)

**Comment by alfixns** [comment]
все, работает) спасибо!!♥
