### ISSUE TITLE
Подтягивает трек, который последний раз слушал на телефоне

### ISSUE THREAD

**Issue by Workezy** [KycTik31/YMD-plus#4]
В данный момент играет этот трек: 
![image](https://github.com/KycTik31/YMD-plus/assets/109183071/77c5507a-1eda-4a5c-88ca-7d6681bac77d)
В активности отображается это:
![image](https://github.com/KycTik31/YMD-plus/assets/109183071/9d102dbf-3267-468c-9f8f-67f1fca7637a)
Время трека идет, но не подтягивает его с пк, трек в статусе слушал с телефона, закрыл там приложения яндекс музыки, все равно не меняется, также пробывал перезапустить скрипт и саму яндекс музыку на ПК, ничего не менялось

**Comment by KycTik31** [comment]
это конечно все жаль, но пофиксить я это не могу т.к это все приколы апи яндекс музыки (оно и так худое), а ячейку в памяти которая хранит название трека я не нашел, возможно когда-нибудь я смогу найти решение этой проблемы, но не сегодня. вообще после того как трек переключится все должно работать нормально
