### ISSUE TITLE
Баг Репорт 

### ISSUE THREAD

**Issue by Memovoff** [KycTik31/YMD-plus#6]
lib 2
web версия ЯМ. Не отображается музыка просто "моя волна" 
Фикс 
Не выбирать "отображать время" 
Хз че те это дало, но знай есть такой баг

**Comment by KycTik31** [comment]
Ну вы ебланы бля, Я же нахуй написал что моя версия для приложения яндекс музыки, а не веб версии, для веб версии юзай премид или прогу другого чела, она на форуме есть
