### ISSUE TITLE
Ошибка после авторизации

### ISSUE THREAD

**Issue by ldl8187433** [KycTik31/YMD-plus#7]
После авторизации происходит ошибка
[error.txt](https://github.com/KycTik31/YMD-plus/files/12327142/error.txt)

**Comment by KycTik31** [comment]
проблема кроется не в программе, а в яндексе, её решить я никак не могу. Единственное что я могу посоветовать, это попробовать включить впн. Если проблема не решилась, надо искать другой способ получения токена
