### ISSUE TITLE
Английский язык.

### ISSUE THREAD

**Issue by Pawuke** [KycTik31/YMD-plus#9]
RPC работает только с русским языком Яндекс Музыки, думаю это можно написать в описание, ибо потратил минут 30 на ревью кода (смешной коммит на преференсе в rpc.py btw)

**Comment by KycTik31** [comment]
я эти ячейки в памяти в рот ебал, мб потом хуки сделаю

**Comment by Pawuke** [comment]
не, просто добавь это в описание на гите, чтобы понимали чокаво

**Comment by KycTik31** [comment]
добавил

**Comment by Pawuke** [comment]
<3
